# Generated by Django 5.2.15 on 2026-07-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='file',
        ),
        migrations.AddField(
            model_name='statement',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='public_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
